#pylint: disable=invalid-envvar-default

import configparser
import os


class Config:
    config = configparser.ConfigParser()
    config.read('src/config/config.ini')

    MQTT_BROKER_IP = config.get('MQTT', 'IP')
    MQTT_BROKER_PORT = config.getint('MQTT', 'PORT')
    MQTT_TIMESTAMP = os.getenv('MQTT', 'MQTT_TIMESTAMP')
    CW_CENTRAL_SERVICE = config['CW_CENTRAL_SERVICE']['BaseURL']
    CW_CENTRAL_SERVICE_IP = config['CW_CENTRAL_SERVICE']['IP']
    CW_CENTRAL_SERVICE_PORT = config['CW_CENTRAL_SERVICE']['PORT']
    CW_LOG_TRACE = config['CW_LOG_TRACE']['BaseURL']
    CW_LOG_TRACE_IP = config['CW_LOG_TRACE']['IP']
    CW_LOG_TRACE_PORT = config['CW_LOG_TRACE']['PORT']
    CW_MESSAGE_SERVICE = config['CW_MESSAGE_SERVICE']['SERVICE']
    CW_MESSAGE_SERVICE_URL = config['CW_MESSAGE_SERVICE']['BaseURL']
    CW_MESSAGE_SERVICE_IP = config['CW_MESSAGE_SERVICE']['IP']
    CW_MESSAGE_SERVICE_PORT = int(config['CW_MESSAGE_SERVICE']['PORT'])

    CW_MESSAGE_DB = config['CW_MESSAGE_DB']['URL']
    CW_MESSAGE_DB_USER = config['CW_MESSAGE_DB']['USER']
    CW_MESSAGE_DB_PASS = config['CW_MESSAGE_DB']['PASS']
    CW_MESSAGE_DB_HOST = config['CW_MESSAGE_DB']['URL']
    CW_MESSAGE_DB_PORT = int(config['CW_MESSAGE_DB']['PORT'])
    CW_MESSAGE_DB_NAME = config['CW_MESSAGE_DB']['NAME']

    # From Dockerfile
    MQTT_BROKER_IP = os.getenv('MQTT_BROKER_IP', MQTT_BROKER_IP)
    MQTT_BROKER_PORT = int(os.getenv('MQTT_BROKER_PORT', MQTT_BROKER_PORT))
    MQTT_TIMESTAMP = os.getenv('MQTT_TIMESTAMP', MQTT_TIMESTAMP)
    CW_CENTRAL_SERVICE = os.getenv('CW_CENTRAL_SERVICE', CW_CENTRAL_SERVICE)
    CW_CENTRAL_SERVICE_IP = os.getenv('CW_CENTRAL_SERVICE_IP', CW_CENTRAL_SERVICE_IP)
    CW_CENTRAL_SERVICE_PORT = int(os.getenv('CW_CENTRAL_SERVICE_PORT', CW_CENTRAL_SERVICE_PORT))
    CW_LOG_TRACE = os.getenv('CW_LOG_TRACE', CW_LOG_TRACE)
    CW_LOG_TRACE_IP = os.getenv('CW_LOG_TRACE_IP', CW_LOG_TRACE_IP)
    CW_LOG_TRACE_PORT = int(os.getenv('CW_LOG_TRACE_PORT', CW_LOG_TRACE_PORT))
    CW_MESSAGE_SERVICE = os.getenv('CW_MESSAGE_SERVICE', CW_MESSAGE_SERVICE)
    CW_MESSAGE_SERVICE_URL = os.getenv('CW_MESSAGE_SERVICE_URL', CW_MESSAGE_SERVICE_URL)
    CW_MESSAGE_SERVICE_IP = os.getenv('CW_MESSAGE_SERVICE_IP', CW_MESSAGE_SERVICE_IP)
    CW_MESSAGE_SERVICE_PORT = int(os.getenv('CW_MESSAGE_SERVICE_PORT', CW_MESSAGE_SERVICE_PORT))

    CW_MESSAGE_DB = os.getenv('CW_MESSAGE_DB', CW_MESSAGE_DB)
    CW_MESSAGE_DB_USER = os.getenv('CW_MESSAGE_DB_USER', CW_MESSAGE_DB_USER)
    CW_MESSAGE_DB_PASS = os.getenv('CW_MESSAGE_DB_PASS', CW_MESSAGE_DB_PASS)
    CW_MESSAGE_DB_HOST = os.getenv('CW_MESSAGE_DB_HOST', CW_MESSAGE_DB_HOST)
    CW_MESSAGE_DB_PORT = int(os.getenv('CW_MESSAGE_DB_PORT', CW_MESSAGE_DB_PORT))
    CW_MESSAGE_DB_NAME = os.getenv('CW_MESSAGE_DB_NAME', CW_MESSAGE_DB_NAME)
